#!/bin/bash

here=`pwd`
DIR_SRC=$here/..
echo $here
echo $DIR_SRC

cd $DIR_SRC
  make PhysConst &> $here/comp.log
cd $here
compOK=`grep -c 'OK' comp.log `

if [ $compOK = '1' ]
then
 echo " PhysConst.exe compilation: OK"
else
 echo " PhysConst.exe compilation: ERROR"
 exit
fi

PCEXE=$DIR_SRC/PhysConst.exe

OldTestsDir=output_28nov2018

./clean

for dat_name in dat*
do
   res_name=`echo res_$dat_name | sed 's/dat_//'`
   echo $res_name
   $PCEXE < $dat_name > $here/$res_name
done


for res_name in res*
do
   echo ---------------------------------------
   echo ----------- $res_name

   ./CompareMass  $res_name
   ./CompareConst $res_name

   echo ---------------------------------------
done

